import type { CartLine } from "./cart";
import type { IsoDateTime, Timestamped } from "./common";

export const ORDER_TYPES = ["TAKEAWAY", "DINE_IN"] as const;
export type OrderType = (typeof ORDER_TYPES)[number];

export const ORDER_STATUSES = [
  "PLACED",
  "ACCEPTED",
  "PREPARING",
  "READY",
  "HANDED_OVER",
  "CANCELLED",
] as const;
export type OrderStatus = (typeof ORDER_STATUSES)[number];

/** The kitchen board columns, in the order work actually flows. */
export const ACTIVE_ORDER_STATUSES = [
  "PLACED",
  "ACCEPTED",
  "PREPARING",
  "READY",
] as const satisfies readonly OrderStatus[];

export const PAYMENT_METHODS = ["ONLINE_UPI", "ONLINE_CARD", "CASH"] as const;
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

export function isOnlineMethod(method: PaymentMethod): boolean {
  return method === "ONLINE_UPI" || method === "ONLINE_CARD";
}

/**
 * UNPAID          dine-in cash, nothing collected yet
 * PAID_UNVERIFIED customer paid online; the cafe has not confirmed receipt
 * VERIFIED        money confirmed in hand or in the account
 * FAILED          admin rejected the payment; customer must pay again
 * REFUNDED        a paid order was cancelled
 */
export const PAYMENT_STATUSES = [
  "UNPAID",
  "PAID_UNVERIFIED",
  "VERIFIED",
  "FAILED",
  "REFUNDED",
] as const;
export type PaymentStatus = (typeof PAYMENT_STATUSES)[number];

export const PAYMENT_ACTIONS = [
  "ONLINE_PAID",
  "PAYMENT_VERIFIED",
  "PAYMENT_REJECTED",
  "CASH_RECEIVED",
  "SWITCHED_TO_ONLINE",
  "REFUNDED",
] as const;
export type PaymentAction = (typeof PAYMENT_ACTIONS)[number];

/** Append-only audit trail of everything that happened to the money. */
export interface PaymentEvent {
  action: PaymentAction;
  method: PaymentMethod;
  amount: number;
  /** 12-digit reference generated by the fake gateway. */
  ref?: string;
  reason?: string;
  byUserId?: string;
  at: IsoDateTime;
}

/** One transition in an order's life, with who made it. */
export interface OrderStatusEvent {
  status: OrderStatus;
  at: IsoDateTime;
  /** User id of the admin who made the change; undefined for the customer. */
  byUserId?: string;
  byName?: string;
  /** Required when status is CANCELLED. */
  reason?: string;
}

/** Each time an admin promised, or re-promised, a ready time. */
export interface ReadyTimeEvent {
  minutes: number;
  at: IsoDateTime;
  byUserId: string;
  reason?: string;
}

/** A cart line frozen at the moment the order was placed. */
export interface OrderLine extends CartLine {
  unitTotal: number;
  lineTotal: number;
}

export interface Order extends Timestamped {
  /** Human-facing order number, e.g. "QB-1042". Also the primary key. */
  id: string;
  /** Short counter-display token, reset every day, e.g. "A23". */
  tokenNumber: string;
  customerId: string;

  orderType: OrderType;
  /** Dine-in only, and optional — staff may fill it in later. */
  tableNumber?: string;

  lines: OrderLine[];
  itemCount: number;
  subtotal: number;
  discount: number;
  couponCode?: string;
  /** Takeaway only; dine-in food is served on a plate. */
  packagingCharge: number;
  /** GST percentage, snapshotted so historic orders stay correct. */
  taxRate: number;
  tax: number;
  total: number;

  paymentMethod: PaymentMethod;
  paymentStatus: PaymentStatus;
  /** 12-digit reference from the simulated gateway. */
  paymentRef?: string;
  cashReceived?: number;
  changeReturned?: number;
  paymentHistory: PaymentEvent[];

  status: OrderStatus;
  statusHistory: OrderStatusEvent[];

  /**
   * Set when an admin accepts the order, not when it is placed — before that
   * the customer only sees a provisional estimate. For scheduled orders it
   * equals `scheduledFor`.
   */
  estimatedReadyAt?: IsoDateTime;
  readyTimeSetBy?: string;
  readyTimeHistory: ReadyTimeEvent[];

  isScheduled: boolean;
  scheduledFor?: IsoDateTime;

  pickupName: string;
  phone: string;
  notes?: string;
  /** True once stock has been deducted, so Accept is never applied twice. */
  stockDeducted: boolean;
}

/** Computed, never stored — see services/orders.ts. */
export interface OrderFlags {
  /** Promised ready time has passed and the order is not READY yet. */
  isOverdue: boolean;
  /** A scheduled order the kitchen should start on now. */
  isDueToStart: boolean;
  /** Waiting for an admin to confirm an online payment. */
  awaitingVerification: boolean;
  /** Dine-in cash that has not been collected yet. */
  cashPending: boolean;
  /** Blocked from handover because the money is not confirmed. */
  blockedFromHandover: boolean;
  /** Customer may still cancel (schedule cutoff / not yet accepted). */
  canCustomerCancel: boolean;
}

/** Filters used by both the admin order table and the customer history. */
export interface OrderFilters {
  status?: OrderStatus | "ACTIVE" | "ALL";
  orderType?: OrderType;
  customerId?: string;
  from?: IsoDateTime;
  to?: IsoDateTime;
  paymentMethod?: PaymentMethod;
  paymentStatus?: PaymentStatus;
  /** Only orders scheduled for later. */
  scheduledOnly?: boolean;
  /** Matches order id, token, pickup name or phone. */
  search?: string;
}
